# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Build
          command: 'g++ -std=c++11 -o fqseek -I src src/fqseek.cpp src/seq_scanner.cpp src/util.cpp'
      - run:
          name: Build Tests
          command: 'g++ -std=c++11 -o test_fqseek -I src src/seq_scanner.cpp src/util.cpp test/test_seq_scanner.cpp'
      - run:
          name: Run Tests
          command: './test_fqseek'
